name: ${pluginName}
version: ${version}
main: io.github.monun.tap.plugin.TapPlugin
api-version: 1.18
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.21
  - org.jetbrains.kotlin:kotlin-reflect:1.6.21
  - org.mariuszgromada.math:MathParser.org-mXparser:4.4.2